### ISSUE TITLE
Trees won't generate in The Betweenlands or in the Twilight Forest

### ISSUE THREAD

**Issue by MrRedstoneA1** [supermassimo/DynamicTrees-ExC#76]
Dynamic trees versions won't generate in The Betweenlands. Only weedwood trees as far as the eye can see. After removing the mods, other trees instantly started generating. Same for the Twilight Forest, only robust twilight oaks everywhere. Not even spruce trees would generate in the arctic areas. Note that I left Dynamic Trees in, that wasn't causing any issues.

Here are all the mod verisons:
Dynamic Trees 1.12.2-0.9.25
Dynamic Trees Betweenlands add-on 1.12.2-1.0.1
Dynamic Trees Twilight Forest add-on 1.12.2-1.2.3
The Betweenlands 1.12.2-3.7.3
Twilight Forest 1.12.2-3.11.1021

Steps to reproduce:
1. install latest versions of all required mods.
2. create a new **superflat** world. Doesn't matter which one as long as no trees can spawn in the overworld. I used the default flat grass one. I also turned structures off.
3.  make a portal to the dimension you want to test. No dynamic trees can spawn there either despite the fact you are no longer in the overworld and trees should spawn in the dimension.

**Comment by Harleyoc1** [comment]
Just tested this and at least for Twilight forest it works fine. Please try updating to the latest versions and test again.

**Comment by MrRedstoneA1** [comment]
I made a typo on the dynamic trees version. All versions are latest. Tried in a clean environment: only the required mods, nothing else. Didn't touch the config files. Same result, no dynamic trees spawn.

**Comment by Harleyoc1** [comment]
You made a typo? This issue was opened around 8 days before I released DT 0.9.25. To verify, you have definitely tested with this version, yes? When I tested it 3 days ago (same setup as you, with a clean env and only required mods) it worked fine.

**Comment by MrRedstoneA1** [comment]
I checked the versions and assumed I made a typo. I must have forgotten that I updated dynamic trees. Yes, I tried with a fresh instance, all latest versions, effectively a clean copy of minecraft. Issue persisted. The only thing I can think of is there's something wrong with the config files. What version of Forge did you use? I have an older version due to some potential incompatibility issues. EDIT: nevermind, updated to latest Forge on clean instance and still nothing.

**Comment by MrRedstoneA1** [comment]
I figured out the problem. Added how to reproduce. I made superflat worlds which have no trees at all and made the portal to the dimension. That was the problem. There were no dynamic trees able to spawn in the overworld so there were none in the dimensions either.
